import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from 'next/router'
import { useMemo } from 'react'
import Animated from '../src/components/shared/Animated'
import Text from '../src/components/shared/Text'
import styles from '../styles/Home.module.css'

const heading = 'patrick_'.split('')
export default function Home() {
  const { asPath: location } = useRouter()
  const onPageActive = useMemo(() => {
    return location === '/'
  }, [location])
  return (
    <div className='h-[85vh] relative flex py-9 items-center justify-end'>
      <Head>
        <title>Patrick Valera Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='text-[25vw] md:text-[20vw] lg:text-[12vw] flex font-[500] '>
        {heading.map((letter, indx) => (
          <Animated key={indx} fromSide={true} show={onPageActive}>
            <h1>{letter}</h1>
          </Animated>
        ))}
      </div>

      <div className='absolute right-0 bottom-0'>
        <Animated show={onPageActive}>
          <Text>Patrick is a software developer</Text>
        </Animated>
        <Animated show={onPageActive}>
          <Text>based in California - U.S. and</Text>
        </Animated>
        <Animated show={onPageActive}>
          <Text>a fullstack web developer.</Text>
        </Animated>
      </div>

      <div className='absolute left-0 bottom-0'>
        <Animated show={onPageActive}>
          <h2 className='text-[5vw] md:text-[3.5vw] lg:text-[2.5vw] leading-[3vw] font-semibold'>Developers</h2>
        </Animated>
        <Animated show={onPageActive}>
          <h2 className='text-[5vw] md:text-[3.5vw] lg:text-[2.5vw] leading-[3vw] font-semibold'>Portfolio</h2>
        </Animated>
        <Animated show={onPageActive}>
          <h2 className='text-[5vw] md:text-[3.5vw] lg:text-[2.5vw] leading-[3vw] font-semibold'>2022</h2>
        </Animated>
      </div>
    </div>
  )
}