import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from 'next/router'
import { useMemo } from 'react'
import Animated from '../src/components/shared/Animated'
import Text from '../src/components/shared/Text'
import styles from '../styles/Home.module.css'

const heading = 'patrick'.split('')
export default function Home() {
  const { asPath: location } = useRouter()
  const onPageActive = useMemo(() => {
    return location === '/'
  }, [location])
  return (
    <div className='h-full border-0 pointer-events-none relative flex items-center px-vw justify-start md:justify-end'>
      <Head>
        <title>Patrick Valera Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='text-[23vw] md:text-[20vw] lg:text-[15vw] flex font-bold '>
        {heading.map((letter, indx) => (
          <Animated key={indx} fromSide={true} delay={indx===4?30:0} show={onPageActive} molasses>
            <h1>{letter}</h1>
          </Animated>
        ))}
        <Animated fromSide={true} show={onPageActive} molasses>
            <h1 className='text-orange-600 font-[500]'>_</h1>
          </Animated>
      </div>

      <div className='absolute left-vw top-[25%] bottom-[unset] md:top-[unset] md:bottom-vw text-[6vw] md:text-[3.5vw] lg:text-[42px] leading-[6.5vw] md:leading-[3.6vw] lg:leading-[51px] font-bold'>
        <Animated show={onPageActive} delay={0}>
          <h2>Developers</h2>
        </Animated>
        <Animated show={onPageActive} delay={100}>
          <h2>Portfolio</h2>
        </Animated>
        <Animated show={onPageActive} delay={180}>
          <h2>2022</h2>
        </Animated>
      </div>

      <div className='absolute left-vw md:left-[unset] right-[unset] md:right-vw bottom-vw text-[3.8vw] md:text-[2.5vw] lg:text-[25px] leading-[5.5vw] md:leading-[2.7vw] lg:leading-[32px] text-left md:text-right font-[500]'>
        <Animated show={onPageActive}>
          <h3>@patrkvee is a software engineer</h3>
        </Animated>
        <Animated show={onPageActive} delay={100}>
          <h3>based in California - U.S. and</h3>
        </Animated>
        <Animated show={onPageActive} delay={180}>
          <h3>a fullstack web developer.</h3>
        </Animated>
      </div>


    </div>
  )
}